server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      bootstrap-servers: localhost:9093
      group-id: "kafka-mongo-comparison"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "spring.json.trusted.packages": "com.examples.kafkakotlin.demo"
    producer:
      bootstrap-servers: localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      org.springframework.kafka.support.serializer.JsonSerializer
#    streams:
#      application-id: "kafka-kotlin-membership"
#      properties:
#        "default.key.serde": org.apache.kafka.common.serialization.Serdes$StringSerde
#        "default.value.serde": org.apache.kafka.common.serialization.Serdes$StringSerde
#        "application.server": localhost:8087
