name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Build Kafka Streams + Run Tests
        working-directory: ./kafka-streams
        run: ./gradlew build
      - name: Code Coverage - Kafka Streams
        working-directory: ./kafka-streams
        run: ./gradlew jacocoTestCoverageVerification
      - name: Build Mongo DB + Run Tests
        working-directory: ./mongodb
        run: ./gradlew build
      - name: Code Coverage - MongoDB
        working-directory: ./mongodb
        run: ./gradlew jacocoTestCoverageVerification